version: '2'

volumes:
    dbvol: {}


services:

    db:
        image: postgres
        volumes: ['dbvol:/var/lib/postgresql/data']
        environment: [POSTGRES_PASSWORD]
        ports: ['5432:5432']

    # broker:
    #     image: rabbitmq

    # miner:
    #     build: .
    #     command: python ./miner/miner.py

    web:
        build: .
        command: python ./webapp/webapp.py
        ports: ['80:5000']
