version: '2'

volumes:
    dbvol: {}

services:
    db:
        image: postgres
        volumes: ['dbvol:/var/lib/postgresql/data']
        environment: [POSTGRES_PASSWORD]
        ports: ['5432:5432']

    # broker:
    #     image: rabbitmq

    # miner:
    #     build: ./app
    #     command: python miner/miner.py

    web:
        build: ./app
        command: python webapp/webapp.py

    # TODO: mount directory containing 'nginx.conf', so we can update
    # proxying rules without needing to restart the proxy container
    # and thus without downtime.
    proxy:
        build: ./proxy
        ports: ['80:80']
